/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminPortalIndexRouteImport } from './routes/admin-portal/index'
import { Route as AdminPortalAccommodationRouteImport } from './routes/admin-portal/accommodation'
import { Route as AdminPortalEventsRouteImport } from './routes/admin-portal/events'
import { Route as AdminPortalFaqsRouteImport } from './routes/admin-portal/faqs'
import { Route as AdminPortalLoginRouteImport } from './routes/admin-portal/login'
import { Route as AdminPortalMessagesRouteImport } from './routes/admin-portal/messages'
import { Route as AdminPortalRequestsRouteImport } from './routes/admin-portal/requests'
import { Route as AdminPortalServicesRouteImport } from './routes/admin-portal/services'
import { Route as AdminPortalSettingsRouteImport } from './routes/admin-portal/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalIndexRoute = AdminPortalIndexRouteImport.update({
  id: '/admin-portal/',
  path: '/admin-portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalAccommodationRoute =
  AdminPortalAccommodationRouteImport.update({
    id: '/admin-portal/accommodation',
    path: '/admin-portal/accommodation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPortalEventsRoute = AdminPortalEventsRouteImport.update({
  id: '/admin-portal/events',
  path: '/admin-portal/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalFaqsRoute = AdminPortalFaqsRouteImport.update({
  id: '/admin-portal/faqs',
  path: '/admin-portal/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalLoginRoute = AdminPortalLoginRouteImport.update({
  id: '/admin-portal/login',
  path: '/admin-portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalMessagesRoute = AdminPortalMessagesRouteImport.update({
  id: '/admin-portal/messages',
  path: '/admin-portal/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalRequestsRoute = AdminPortalRequestsRouteImport.update({
  id: '/admin-portal/requests',
  path: '/admin-portal/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalServicesRoute = AdminPortalServicesRouteImport.update({
  id: '/admin-portal/services',
  path: '/admin-portal/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalSettingsRoute = AdminPortalSettingsRouteImport.update({
  id: '/admin-portal/settings',
  path: '/admin-portal/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRoute
  '/admin-portal/accommodation': typeof AdminPortalAccommodationRoute
  '/admin-portal/events': typeof AdminPortalEventsRoute
  '/admin-portal/faqs': typeof AdminPortalFaqsRoute
  '/admin-portal/login': typeof AdminPortalLoginRoute
  '/admin-portal/messages': typeof AdminPortalMessagesRoute
  '/admin-portal/requests': typeof AdminPortalRequestsRoute
  '/admin-portal/services': typeof AdminPortalServicesRoute
  '/admin-portal/settings': typeof AdminPortalSettingsRoute
  '/admin-portal/': typeof AdminPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRoute
  '/admin-portal/accommodation': typeof AdminPortalAccommodationRoute
  '/admin-portal/events': typeof AdminPortalEventsRoute
  '/admin-portal/faqs': typeof AdminPortalFaqsRoute
  '/admin-portal/login': typeof AdminPortalLoginRoute
  '/admin-portal/messages': typeof AdminPortalMessagesRoute
  '/admin-portal/requests': typeof AdminPortalRequestsRoute
  '/admin-portal/services': typeof AdminPortalServicesRoute
  '/admin-portal/settings': typeof AdminPortalSettingsRoute
  '/admin-portal': typeof AdminPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRoute
  '/admin-portal/accommodation': typeof AdminPortalAccommodationRoute
  '/admin-portal/events': typeof AdminPortalEventsRoute
  '/admin-portal/faqs': typeof AdminPortalFaqsRoute
  '/admin-portal/login': typeof AdminPortalLoginRoute
  '/admin-portal/messages': typeof AdminPortalMessagesRoute
  '/admin-portal/requests': typeof AdminPortalRequestsRoute
  '/admin-portal/services': typeof AdminPortalServicesRoute
  '/admin-portal/settings': typeof AdminPortalSettingsRoute
  '/admin-portal/': typeof AdminPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accommodation'
    | '/contact'
    | '/events'
    | '/faq'
    | '/services'
    | '/admin-portal/accommodation'
    | '/admin-portal/events'
    | '/admin-portal/faqs'
    | '/admin-portal/login'
    | '/admin-portal/messages'
    | '/admin-portal/requests'
    | '/admin-portal/services'
    | '/admin-portal/settings'
    | '/admin-portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accommodation'
    | '/contact'
    | '/events'
    | '/faq'
    | '/services'
    | '/admin-portal/accommodation'
    | '/admin-portal/events'
    | '/admin-portal/faqs'
    | '/admin-portal/login'
    | '/admin-portal/messages'
    | '/admin-portal/requests'
    | '/admin-portal/services'
    | '/admin-portal/settings'
    | '/admin-portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accommodation'
    | '/contact'
    | '/events'
    | '/faq'
    | '/services'
    | '/admin-portal/accommodation'
    | '/admin-portal/events'
    | '/admin-portal/faqs'
    | '/admin-portal/login'
    | '/admin-portal/messages'
    | '/admin-portal/requests'
    | '/admin-portal/services'
    | '/admin-portal/settings'
    | '/admin-portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  ServicesRoute: typeof ServicesRoute
  AdminPortalAccommodationRoute: typeof AdminPortalAccommodationRoute
  AdminPortalEventsRoute: typeof AdminPortalEventsRoute
  AdminPortalFaqsRoute: typeof AdminPortalFaqsRoute
  AdminPortalLoginRoute: typeof AdminPortalLoginRoute
  AdminPortalMessagesRoute: typeof AdminPortalMessagesRoute
  AdminPortalRequestsRoute: typeof AdminPortalRequestsRoute
  AdminPortalServicesRoute: typeof AdminPortalServicesRoute
  AdminPortalSettingsRoute: typeof AdminPortalSettingsRoute
  AdminPortalIndexRoute: typeof AdminPortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/': {
      id: '/admin-portal/'
      path: '/admin-portal'
      fullPath: '/admin-portal/'
      preLoaderRoute: typeof AdminPortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/accommodation': {
      id: '/admin-portal/accommodation'
      path: '/admin-portal/accommodation'
      fullPath: '/admin-portal/accommodation'
      preLoaderRoute: typeof AdminPortalAccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/events': {
      id: '/admin-portal/events'
      path: '/admin-portal/events'
      fullPath: '/admin-portal/events'
      preLoaderRoute: typeof AdminPortalEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/faqs': {
      id: '/admin-portal/faqs'
      path: '/admin-portal/faqs'
      fullPath: '/admin-portal/faqs'
      preLoaderRoute: typeof AdminPortalFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/login': {
      id: '/admin-portal/login'
      path: '/admin-portal/login'
      fullPath: '/admin-portal/login'
      preLoaderRoute: typeof AdminPortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/messages': {
      id: '/admin-portal/messages'
      path: '/admin-portal/messages'
      fullPath: '/admin-portal/messages'
      preLoaderRoute: typeof AdminPortalMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/requests': {
      id: '/admin-portal/requests'
      path: '/admin-portal/requests'
      fullPath: '/admin-portal/requests'
      preLoaderRoute: typeof AdminPortalRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/services': {
      id: '/admin-portal/services'
      path: '/admin-portal/services'
      fullPath: '/admin-portal/services'
      preLoaderRoute: typeof AdminPortalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal/settings': {
      id: '/admin-portal/settings'
      path: '/admin-portal/settings'
      fullPath: '/admin-portal/settings'
      preLoaderRoute: typeof AdminPortalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  ServicesRoute: ServicesRoute,
  AdminPortalAccommodationRoute: AdminPortalAccommodationRoute,
  AdminPortalEventsRoute: AdminPortalEventsRoute,
  AdminPortalFaqsRoute: AdminPortalFaqsRoute,
  AdminPortalLoginRoute: AdminPortalLoginRoute,
  AdminPortalMessagesRoute: AdminPortalMessagesRoute,
  AdminPortalRequestsRoute: AdminPortalRequestsRoute,
  AdminPortalServicesRoute: AdminPortalServicesRoute,
  AdminPortalSettingsRoute: AdminPortalSettingsRoute,
  AdminPortalIndexRoute: AdminPortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
